### ISSUE TITLE
Directives are not well transpiled. 

### ISSUE THREAD

**Issue by manuelalcantara-natgeo** [wenfzhao/graphql-type-inheritance#1]
I have a problem with a schema that contains a directive. 
```
directive @upper on FIELD_DEFINITION
type Query {
  getAccessToken(code: String!): String! @upper
  getLoggedUser(): String!
}
```
In that file, I am getting this string after transpiled it. 
```
"type Query { \n    getAccessToken(code: String!): String! getLoggedUser(): String!\n}\n
```

As you can see there is not line break between query names, so makeExecutableSchema does not work. Also the directives were deleted. 

Is this a bug? 

Thanks for your help.

**Comment by wenfzhao** [comment]
@manuelalcantara-natgeo Are you still have problem transpiling your schema with directives? If so please include the version number of the library, and sample code to reproduce it.
